name = "streamist-cdn"
type = "javascript"
account_id = "1a5d304db1c315f0731d67e097a1ee6c"
workers_dev = false
zone_id = "741bbcd1f6bdaf9e0661e06ccbfb5648"
compatibility_date = "2022-03-01"

[build.upload]
format = "modules"
main = "./index.mjs"

[env.production]
name = "streamist-cdn-production"
route = "cdn.stst.page/*"

[env.staging]
name = "streamist-cdn-staging"
route = "staging-cdn.stst.page/*"
