version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file: database.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - db-network

  nodejs:
    image: streamist-server
    container_name: nodejs
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network
      - batch-network
      - db-network
    env_file: server.env
    environment:
      - API_SERVER_PORT=8080
      - API_BASE_PATH=/brp-api
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/gapp-credentials.json
    volumes:
      - ./gapp-credentials.json:/credentials/gapp-credentials.json:ro

  batch:
    image: streamist-server
    container_name: batch
    restart: always
    entrypoint: /app/batch.sh
    depends_on:
      - nodejs
    networks:
      - batch-network
      - db-network
    env_file: server.env
    environment:
      - API_SERVER_PORT=8080
      - API_BASE_PATH=/dummy
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/gapp-credentials.json
    volumes:
      - ./gapp-credentials.json:/credentials/gapp-credentials.json:ro

  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/lego/cert.pem:/certificates/cert.pem:ro
      - ./cfip.txt:/usr/local/etc/haproxy/cfip.txt:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - nodejs
    networks:
      - app-network

  postgres_backup:
    image: eeshugerman/postgres-backup-s3:14
    container_name: postgres_backup
    restart: always
    depends_on:
      - postgres
    networks:
      - db-network
    env_file: database_backup.env
    environment:
      - SCHEDULE=@daily
      - S3_PREFIX=backup
      - POSTGRES_HOST=postgres
      - S3_REGION=ap-northeast-1
      - S3_ENDPOINT=https://s3.ap-northeast-1.wasabisys.com

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
  batch-network:
    driver: bridge
