name = "streamist-ws"
type = "javascript"
account_id = "1a5d304db1c315f0731d67e097a1ee6c"
workers_dev = false
zone_id = "fe613e64ce8637c9fd462f6164d2f2f6"
compatibility_date = "2022-03-01"

[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  {name = "DO", class_name = "DO"},
]

[[migrations]]
tag = "v1"
new_classes = ["DO"]

[env.production]
name = "streamist-ws-production"
durable_objects.bindings = [
  {name = "DO", class_name = "DO"},
]
routes = [
  "streamist.app/ws/*",
  "production-workers-ws.streamist.app/*",
]

[env.staging]
name = "streamist-ws-staging"
durable_objects.bindings = [
  {name = "DO", class_name = "DO"},
]
routes = [
  "staging.streamist.app/ws/*",
  "staging-workers-ws.streamist.app/*",
]
