import { setOSCredentials } from '$shared-server/osOperations';
import {
  SECRET_TRANSCODER_WASABI_ACCESS_KEY_ID,
  SECRET_TRANSCODER_WASABI_SECRET_ACCESS_KEY,
} from './env';

setOSCredentials({
  WASABI_ACCESS_KEY_ID: SECRET_TRANSCODER_WASABI_ACCESS_KEY_ID,
  WASABI_SECRET_ACCESS_KEY: SECRET_TRANSCODER_WASABI_SECRET_ACCESS_KEY,
});
