// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    README: typeof import('./components/README.md')['default']
    SAlbum: typeof import('./components/SAlbum.vue')['default']
    SConditionalLink: typeof import('./components/SConditionalLink.vue')['default']
    SEllipsisTooltip: typeof import('./components/SEllipsisTooltip.vue')['default']
    SNoImage: typeof import('./components/SNoImage.vue')['default']
    SNullableImage: typeof import('./components/SNullableImage.vue')['default']
    SPlaybackControl: typeof import('./components/SPlaybackControl.vue')['default']
    SPlaylist: typeof import('./components/SPlaylist.vue')['default']
    SQueue: typeof import('./components/SQueue.vue')['default']
    SSeekBar: typeof import('./components/SSeekBar.vue')['default']
    SSlider: typeof import('./components/SSlider.vue')['default']
    STrackList: typeof import('./components/STrackList.vue')['default']
    SUploader: typeof import('./components/SUploader.vue')['default']
    SUploaderList: typeof import('./components/SUploaderList.vue')['default']
    SUploaderListItem: typeof import('./components/SUploaderListItem.vue')['default']
    SVolumeControl: typeof import('./components/SVolumeControl.vue')['default']
  }
}

export { }
