// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Album: typeof import('./components/Album.vue')['default']
    ConditionalLink: typeof import('./components/ConditionalLink.vue')['default']
    EllipsisTooltip: typeof import('./components/EllipsisTooltip.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    NoImage: typeof import('./components/NoImage.vue')['default']
    NullableImage: typeof import('./components/NullableImage.vue')['default']
    PlaybackControl: typeof import('./components/PlaybackControl.vue')['default']
    Playlist: typeof import('./components/Playlist.vue')['default']
    Queue: typeof import('./components/Queue.vue')['default']
    README: typeof import('./components/README.md')['default']
    SSeekBar: typeof import('./components/SSeekBar.vue')['default']
    SSlider: typeof import('./components/SSlider.vue')['default']
    TrackList: typeof import('./components/TrackList.vue')['default']
    Uploader: typeof import('./components/Uploader.vue')['default']
  }
}

export { }
