export const ACCURATE_TIME_IGNORE_PING_THRESHOLD = 10_000;
export const ACCURATE_TIME_PING_INTERVAL = 60_000;
export const ACCURATE_TIME_INITIAL_PING_DELAY = 1000;
export const ACCURATE_TIME_CLIENT_CLOCK_SKEW_THRESHOLD = 2000;
export const ACCURATE_TIME_CLIENT_CLOCK_CHECK_INTERVAL = 20_000;
