import { config } from 'dotenv';

config();

const API_SERVER_PORT = parseInt(process.env.API_SERVER_PORT || '8080', 10);
const API_BASE_PATH = process.env.API_BASE_PATH ?? '';
const API_ORIGIN = process.env.API_ORIGIN ?? '';
const SECRET_API_JWT_SECRET = process.env.SECRET_API_JWT_SECRET ?? '';
const SECRET_TRANSCODER_CALLBACK_SECRET =
  process.env.SECRET_TRANSCODER_CALLBACK_SECRET ?? '';
const SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID =
  process.env.SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID ?? '';
const SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY =
  process.env.SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY ?? '';
const SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID =
  process.env.SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID ?? '';
const SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY =
  process.env.SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY ?? '';

if (!SECRET_API_JWT_SECRET) {
  throw new Error('SECRET_API_JWT_SECRET is not defined');
}

if (!SECRET_TRANSCODER_CALLBACK_SECRET) {
  throw new Error('SECRET_TRANSCODER_CALLBACK_SECRET is not defined');
}

if (!SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID) {
  throw new Error('SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID is not defined');
}

if (!SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY) {
  throw new Error(
    'SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY is not defined'
  );
}

if (!SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID) {
  throw new Error('SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID is not defined');
}

if (!SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY) {
  throw new Error('SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY is not defined');
}

export {
  API_SERVER_PORT,
  API_BASE_PATH,
  API_ORIGIN,
  SECRET_API_JWT_SECRET,
  SECRET_TRANSCODER_CALLBACK_SECRET,
  SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID,
  SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY,
  SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID,
  SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY,
};
