import { config } from 'dotenv';

const IS_DEV = process.env.NODE_ENV === 'development';

if (IS_DEV) {
  config({
    path: '../shared-server/env/development.env',
  });
}

const API_SERVER_PORT = parseInt(process.env.API_SERVER_PORT || '8080', 10);
const API_BASE_PATH = process.env.API_BASE_PATH ?? '';
const API_ORIGIN = process.env.API_ORIGIN ?? '';
const SECRET_API_JWT_SECRET = process.env.SECRET_API_JWT_SECRET ?? '';
const SECRET_CDN_JWT_SECRET = process.env.SECRET_CDN_JWT_SECRET ?? '';
const SECRET_REFRESH_TOKEN_JWT_SECRET =
  process.env.SECRET_REFRESH_TOKEN_JWT_SECRET ?? '';
const SECRET_TRANSCODER_CALLBACK_SECRET =
  process.env.SECRET_TRANSCODER_CALLBACK_SECRET ?? '';
const SECRET_API_PROXY_AUTH_TOKEN =
  process.env.SECRET_API_PROXY_AUTH_TOKEN ?? '';
const SECRET_SERVER_WASABI_ACCESS_KEY_ID =
  process.env.SECRET_SERVER_WASABI_ACCESS_KEY_ID ?? '';
const SECRET_SERVER_WASABI_SECRET_ACCESS_KEY =
  process.env.SECRET_SERVER_WASABI_SECRET_ACCESS_KEY ?? '';
const SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID =
  process.env.SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID ?? '';
const SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY =
  process.env.SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY ?? '';
const SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID =
  process.env.SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID ?? '';
const SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY =
  process.env.SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY ?? '';
const HCAPTCHA_SITE_KEY_REGISTRATION =
  process.env.HCAPTCHA_SITE_KEY_REGISTRATION ?? '';
const SECRET_HCAPTCHA_SECRET = process.env.SECRET_HCAPTCHA_SECRET ?? '';

if (!API_ORIGIN) {
  // this is needed for the transcoder to call back to the API server
  throw new Error('API_ORIGIN is not defined');
}

if (!SECRET_API_JWT_SECRET) {
  throw new Error('SECRET_API_JWT_SECRET is not defined');
}

if (!SECRET_CDN_JWT_SECRET) {
  throw new Error('SECRET_CDN_JWT_SECRET is not defined');
}

if (!SECRET_REFRESH_TOKEN_JWT_SECRET) {
  throw new Error('SECRET_REFRESH_TOKEN_JWT_SECRET is not defined');
}

if (!SECRET_TRANSCODER_CALLBACK_SECRET) {
  throw new Error('SECRET_TRANSCODER_CALLBACK_SECRET is not defined');
}

if (!SECRET_SERVER_WASABI_ACCESS_KEY_ID) {
  throw new Error('SECRET_SERVER_WASABI_ACCESS_KEY_ID is not defined');
}

if (!SECRET_SERVER_WASABI_SECRET_ACCESS_KEY) {
  throw new Error('SECRET_SERVER_WASABI_SECRET_ACCESS_KEY is not defined');
}

if (!SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID) {
  throw new Error('SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID is not defined');
}

if (!SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY) {
  throw new Error(
    'SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY is not defined'
  );
}

if (!SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID) {
  throw new Error('SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID is not defined');
}

if (!SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY) {
  throw new Error('SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY is not defined');
}

if (!SECRET_API_PROXY_AUTH_TOKEN) {
  throw new Error('SECRET_API_PROXY_AUTH_TOKEN is not defined');
}

if (!IS_DEV && !HCAPTCHA_SITE_KEY_REGISTRATION) {
  throw new Error('HCAPTCHA_SITE_KEY_REGISTRATION is not defined');
}

if (!IS_DEV && !SECRET_HCAPTCHA_SECRET) {
  throw new Error('SECRET_HCAPTCHA_SECRET is not defined');
}

export {
  API_SERVER_PORT,
  API_BASE_PATH,
  API_ORIGIN,
  SECRET_API_JWT_SECRET,
  SECRET_CDN_JWT_SECRET,
  SECRET_REFRESH_TOKEN_JWT_SECRET,
  SECRET_TRANSCODER_CALLBACK_SECRET,
  SECRET_API_PROXY_AUTH_TOKEN,
  SECRET_SERVER_WASABI_ACCESS_KEY_ID,
  SECRET_SERVER_WASABI_SECRET_ACCESS_KEY,
  SECRET_USER_DOWNLOAD_WASABI_ACCESS_KEY_ID,
  SECRET_USER_DOWNLOAD_WASABI_SECRET_ACCESS_KEY,
  SECRET_USER_UPLOAD_WASABI_ACCESS_KEY_ID,
  SECRET_USER_UPLOAD_WASABI_SECRET_ACCESS_KEY,
  HCAPTCHA_SITE_KEY_REGISTRATION,
  SECRET_HCAPTCHA_SECRET,
};
