name: 'Deploy CDN'

concurrency:
  group: deploy_cdn-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'packages/cdn/**'
      - 'packages/shared/**'
      - 'packages/shared-server/**'
      - '.github/workflows/deploy_cdn.yml'

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo "TARGET_BUILD_REV=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set env (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "DEPLOY_ENV=PRODUCTION" >> $GITHUB_ENV
          echo "TARGET_NODE_ENV=production" >> $GITHUB_ENV
          echo "APP_ORIGIN=https://streamist.app" >> $GITHUB_ENV

      - name: Set env (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "DEPLOY_ENV=STAGING" >> $GITHUB_ENV
          echo "TARGET_NODE_ENV=staging" >> $GITHUB_ENV
          echo "APP_ORIGIN=https://staging.streamist.app" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run generate
      - run: pnpm run build:cdn
      - name: Deploy CDN to Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.SECRET_GH_CF_API_TOKEN }}
          environment: ${{ env.TARGET_NODE_ENV }}
          workingDirectory: 'packages/cdn'
          secrets: |
            APP_ORIGIN
            SECRET_CDN_CACHE_SECURITY_KEY_HMAC_SECRET
            SECRET_CDN_JWT_SECRET
            SECRET_CDN_STORAGE_ACCESS_REFERRER
        env:
          SECRET_CDN_CACHE_SECURITY_KEY_HMAC_SECRET: ${{ secrets[format('{0}_SECRET_CDN_CACHE_SECURITY_KEY_HMAC_SECRET', env.DEPLOY_ENV)] }}
          SECRET_CDN_JWT_SECRET: ${{ secrets[format('{0}_SECRET_CDN_JWT_SECRET', env.DEPLOY_ENV)] }}
          SECRET_CDN_STORAGE_ACCESS_REFERRER: ${{ secrets[format('{0}_SECRET_CDN_STORAGE_ACCESS_REFERRER', env.DEPLOY_ENV)] }}
