name: 'Deploy Frontend'

concurrency:
  group: deploy_frontend-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'packages/frontend/**'
      - '!packages/frontend/**/*.d.ts'
      - 'packages/shared/**'
      - '.github/workflows/deploy_frontend.yml'

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: echo "TARGET_BUILD_REV=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set env (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "DEPLOY_ENV=PRODUCTION" >> $GITHUB_ENV
          echo "TARGET_NODE_ENV=production" >> $GITHUB_ENV
          echo "VITE_CDN_ORIGIN=https://cdn.stst.page" >> $GITHUB_ENV

      - name: Set env (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "DEPLOY_ENV=STAGING" >> $GITHUB_ENV
          echo "TARGET_NODE_ENV=staging" >> $GITHUB_ENV
          echo "VITE_CDN_ORIGIN=https://staging-cdn.stst.page" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run generate
      - run: pnpm run build:client -- -- --mode $TARGET_NODE_ENV
        env:
          VITE_HCAPTCHA_SITE_KEY_FOR_REGISTRATION: ${{ secrets[format('{0}_HCAPTCHA_SITE_KEY_FOR_REGISTRATION', env.DEPLOY_ENV)] }}
      - run: |
          mkdir -p packages/frontend/build
          mv packages/frontend/dist packages/frontend/build/
          cp -r packages/frontend/functions packages/frontend/build/
      - name: Deploy to build repository
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:${{ secrets[format('SECRET_GH_{0}_BUILD_REPOSITORY_NAME', env.DEPLOY_ENV)] }}
          BRANCH: main
          FOLDER: packages/frontend/build
          SSH_PRIVATE_KEY: ${{ secrets[format('SECRET_GH_{0}_BUILD_REPOSITORY_DEPLOY_KEY', env.DEPLOY_ENV)] }}
