name: 'Staging: Build and deploy Transcoder'

on:
  push:
    branches:
      - staging
    paths:
      - 'packages/transcoder/**'
      - '.github/workflows/staging_deploy_transcoder.yml'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run generate
      - run: |
          cd packages/operation
          pnpm run start -- initAll staging
      - run: pnpm run build:transcoder
        env:
          TARGET_NODE_ENV: staging
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SECRET_GH_STAGING_DEPLOY_TRANSCODER_LAMBDA_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_GH_STAGING_DEPLOY_TRANSCODER_LAMBDA_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: projects/532903232967/locations/global/workloadIdentityPools/transcoder-deploy-github-actions/providers/github
          service_account: transcoder-deploy@streamist-staging.iam.gserviceaccount.com
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy transcoder to AWS Lambda and Google Cloud Run
        run: |
          cd packages/transcoder
          cp ../operation/result/staging/deploy.sh .
          chmod +x deploy.sh
          ./deploy.sh
