name: 'Deploy Frontend'

on:
  push:
    branches:
      - staging
    paths:
      - 'packages/frontend/**'
      - '!packages/frontend/**/*.d.ts'
      - 'packages/shared/**'
      - '.github/workflows/staging_deploy_frontend.yml'

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:
      - name: Set env (Staging)
        if: ${{ github.ref == 'refs/heads/staging' }}
        run: |
          echo "DEPLOY_ENV=STAGING" >> $GITHUB_ENV
          echo "TARGET_NODE_ENV=staging" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run generate
      - run: pnpm run build:client -- -- --mode $TARGET_NODE_ENV
        env:
          VITE_CDN_ORIGIN: ${{ secrets[format('{0}_CDN_ORIGIN', env.DEPLOY_ENV)] }}
          VITE_HCAPTCHA_SITE_KEY_FOR_REGISTRATION: ${{ secrets[format('{0}_HCAPTCHA_SITE_KEY_FOR_REGISTRATION', env.DEPLOY_ENV)] }}
      - run: |
          mkdir -p packages/frontend/build
          mv packages/frontend/dist packages/frontend/build/
          cp -r packages/frontend/functions packages/frontend/build/
      - name: Deploy to build repository
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:${{ secrets.SECRET_GH_BUILD_REPOSITORY_NAME }}.git
          BRANCH: staging
          FOLDER: packages/frontend/build
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_GH_BUILD_REPOSITORY_DEPLOY_KEY }}
