name: 'Test'

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '.husky/**'
      - '.vscode/**'
      - 'docs/**'
      - 'frontend/locales/**'
      - 'frontend/public/**'
  pull_request:
    types: [opened, reopened]
    branches:
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Setup git username and email
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run generate
      - run: pnpm run lint
      - run: pnpm run typecheck
      - run: pnpm run test
      - run: pnpm run build
        env:
          TARGET_NODE_ENV: production
      # GITHUB_TOKEN does not trigger new workflow run
      # https://stackoverflow.com/a/67551255
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # we had to either use PAT or merge manually and chose the latter
      - name: Create pull request
        if: github.ref == 'refs/heads/develop'
        run: |
          gh pr create -B staging -t "[Staging] Deploy" -b "Commit: $GITHUB_SHA"
          # gh pr merge --auto -m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
